### ISSUE TITLE
1.5.0 Upgrade is crashing homebridge with no other changes

### ISSUE THREAD

**Issue by BenDaSpur** [goedh452/homebridge-http-sprinkler#19]
If I upgrade to 1.5.0 my homebridge crashes with this error:
`SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HttpSprinkler.httpRequest (/usr/lib/node_modules/homebridge-http-sprinkler/index.js:102:24)
    at HttpSprinkler.pollingtoevent.interval (/usr/lib/node_modules/homebridge-http-sprinkler/index.js:48:12)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-http-sprinkler/node_modules/polling-to-event/index.js:77:5)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)`
    
There are no other changes being made other than this upgrade. Are there any required changes with 1.5.0?

**Comment by goedh452** [comment]
I merged a pull request and probably that broke something. I'll look into it.

**Comment by goedh452** [comment]
I removed the changes from the merge request. Everything is working fine now. Please upgrade to version 1.5.1.
